### ISSUE TITLE
ArrayIndexOutOfBoundsException due to missing & 0xFF in MortonTable256 lookup

### ISSUE THREAD

**Issue by adamsbart** [eren-ck/MortonLib#1] opened 2020-04-08 11:54 UTC
The encode method should be like this:

MortonTable256[(y >> 8)&0xFF]

for the lookups instead of

MortonTable256[(y >> 8)]

y>>8 can amount to 256 which leads to an index out of bounds in the array of 256 elements.

**Comment by eren-ck** [comment] 2020-05-15 07:42
Thanks for pointing that out. The issue is fixed with 9c6a6fb.

Cheers

**Closed as completed by eren-ck** 2020-05-15 07:42 UTC
